language: python
python:
  - "3.9"
before_install:
  - pip install -U pip
  - pip install -U pytest
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 4d88a700-0288-415e-ba58-839ffb7a06fc
